version: "3"
services:
  auth:
    restart: always
    image: ghazouanihm/weatherapp-auth:1.0
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PASSWORD: my-secret-pw
    networks:
      - app-net
  ui:
    restart: always
    image: ghazouanihm/weatherapp-ui:1.0
    depends_on:
      - auth
      - weather
    environment:
      AUTH_HOST: auth
      AUTH_PORT: 8080
      WEATHER_HOST: weather
      WEATHER_PORT: 5000
    ports:
      - "3000:3000"
    networks:
      - app-net
  weather:
    restart: always
    image: ghazouanihm/weatherapp-weather:1.0
    environment:
      APIKEY: 9bf8ba9657ba467ca4b123541231105
    networks:
      - app-net
  db:
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - app-net
    volumes:
      - ./db-data:/var/lib/mysql

networks:
  app-net:
    driver: bridge
volumes:
  db-data: