---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    monitoring: prometheus
    istio-injection: enabled

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app-istio-canary-deployment-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/GhazouaniHichem/microservices-weather-app-gitops.git
    targetRevision: main
    path: ./kubernetes/weather-app-istio-deployment/
  destination: 
    server: https://kubernetes.default.svc
    namespace: staging

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true